### ISSUE TITLE
English version of `info.md`

### ISSUE THREAD

**Issue by hpretl** [RobinH08/JKU-TT06-FlappyBird#1]
Could you please translate this doc to English? https://github.com/RobinH08/JKU-TT06-FlappyBird/blob/main/docs/info.md

Thanks!

**Comment by RobinH08** [comment]
done

**Comment by RobinH08** [comment]
> Could you please translate this doc to English? https://github.com/RobinH08/JKU-TT06-FlappyBird/blob/main/docs/info.md
> 
> Thanks!

done
